/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package excel.app;



import static excel.app.MessageUtils.getMessage;


public class App {
    public static void main(String[] args) {
        System.out.println(getMessage());
    }
}
